sirensolutions/G6

- packages/core/src/graph/graph.ts
This adds an option to perform an animated translate.
I added this to allow performing an animated padding, example below (implemented with graphin)
https://user-images.githubusercontent.com/2861371/142659666-d74740d2-8c7c-44c0-85ba-765d0f9bdbb0.mp4
> feat: add translate animation

- packages/core/src/graph/graph.ts
- packages/core/src/interface/graph.ts
- packages/pc/src/behavior/zoom-canvas.ts
This is to support animation in the zoomTo function (quite easy at this point)
Additionally, I updated the zoom-canvas behavior to support the new animation
Upstream https://github.com/antvis/G6/pull/3322
> feat: add animated zoomTo

- packages/core/src/graph/graph.ts
- packages/core/src/interface/graph.ts
- packages/pc/src/behavior/zoom-canvas.ts
> Inve 16600 2

- packages/core/src/graph/graph.ts
- packages/core/tests/unit/graph/graph-spec.ts
Sibiling of https://github.com/antvis/G6/pull/3473
> fix: allow enabling stack operations at runtime

- packages/core/src/graph/graph.ts
With this PR the expansion function will automatically compute the best (based on some internal parameters) number of layers and the best number of nodes per layer
How to test:
- Download this demo app -> [demoreactapp-main.zip](https://github.com/sirensolutions/G6/files/7926327/demoreactapp-main.zip)
- run `npm install`
- Check out this branch, go into the packages/core folder and run `npm link`
- go to the demo app folder and run `npm link @antv/g6-core`
- now start the demo app with npm start
You'll end up with a single node on the screen. Pressing the `E` key will cause the expansion (some nodes should pop up on the top left corner). Now, pressing the `U` key will produce a console log showing the undo/redo stacks. You should see the expansion operation in the stack
Notes:
- You can …
> [INVE-17798] Add expansion placeholder

- packages/pc/src/behavior/drag-combo.ts
Upstream: https://github.com/antvis/G6/pull/3701
> [INVE-18622] Update combo edge at the same time onDrag

- packages/core/src/graph/graph.ts
Upstream: https://github.com/antvis/G6/pull/3585
> [INVE-0000] Animate positions only when auto paint is on

- packages/core/src/graph/controller/view.ts
- packages/core/src/graph/graph.ts
- packages/core/src/interface/graph.ts
Upstream: https://github.com/antvis/G6/pull/3637
> [INVE-17480] Animate fitCenter and fitView

- packages/core/src/element/node.ts
- packages/core/src/types/index.ts
- packages/core/src/util/graphic.ts
- packages/core/tests/unit/shape/node-spec.ts
- packages/core/tests/unit/util/graphic-spec.ts
https://sirensolutions.atlassian.net/browse/INVE-18384
Upstream: https://github.com/antvis/G6/pull/3690
> [INVE-18384] Truncate node labels

- packages/core/src/graph/controller/view.ts
- packages/core/src/graph/graph.ts
- packages/core/src/util/graphic.ts
- packages/core/src/util/math.ts
This PR reimplements the animated fitView function to perform a single smooth animation.
Please test it with rules too to ensure I didn't miss anything
> [INVE-19035] feat: rework animated fitView

- packages/pc/src/behavior/drag-combo.ts
[INVE-19108](https://sirensolutions.atlassian.net/browse/INVE-19108)
> fix: Disabled 'UpdateComboTree' pushing action into the stack when combo was being dragged

- packages/core/src/graph/graph.ts
- packages/core/tests/unit/graph/graph-spec.ts
This will allow to set initial state on items added to graph.
> [INVE-19202] feat: Make it possible to pass initial states on items

- packages/react-node/package.json
Tried running bootstrap and got this 
seems like inconsistency in versions
> Fixed inconsistent version

- packages/pc/src/behavior/drag-combo.ts
- packages/pc/tests/unit/behavior/drag-combo-spec.ts
https://user-images.githubusercontent.com/15673201/192486633-0a2818d6-0d7d-43bd-93af-fd2d6b9c753c.mov
> [INVE-19150] fixes issue where drag on unselected combos did not work

- packages/core/src/graph/controller/item.ts
- packages/core/src/graph/graph.ts
- packages/pc/src/behavior/drag-node.ts
The individual commits should be self explanatory :)
> feat: performance tweaks

- packages/core/src/graph/graph.ts
With this change, the user is able to react to stackevent changes triggered by specific operations
> [INVE-19507] feat: more descriptive stackchange events

- packages/pc/src/behavior/drag-canvas.ts
[INVE-19809]
Not needed
Not needed
[INVE-19809]: https://sirensolutions.atlassian.net/browse/INVE-19809
> [INVE-19809] Fixed drag-canvas with ctrl button pressed.

- packages/core/package.json
- packages/core/src/global.ts
- packages/element/package.json
- packages/g6/package.json
- packages/g6/src/index.ts
- packages/pc/package.json
- packages/pc/src/global.ts
- packages/plugin/package.json
- packages/react-node/package.json
- packages/site/package.json
> [INVE-19651] Bumped version

- packages/pc/src/behavior/drag-combo.ts
- packages/pc/src/behavior/drag-node.ts
Before:
https://user-images.githubusercontent.com/2861371/215097019-ad512a5f-8a6d-4c73-9cdc-5bfadc6d00bc.mp4
After:
https://user-images.githubusercontent.com/2861371/215097037-68edfb60-76e5-4814-b12d-36ccd76df9f8.mp4
> [INVE-20390] Update combos during drag operations

- packages/core/package.json
- packages/element/package.json
- packages/g6/package.json
- packages/pc/package.json
- packages/pc/src/behavior/drag-combo.ts
- packages/pc/src/behavior/drag-node.ts
- packages/plugin/package.json
- packages/react-node/package.json
- packages/site/package.json
[INVE-20979]
[INVE-20979]: https://sirensolutions.atlassian.net/browse/INVE-20979
> [INVE-20979] Fixed node dragging starting one event too late.

- CHANGELOG.md
- packages/core/jest.config.js
- packages/core/package.json
- packages/core/src/global.ts
- packages/core/src/graph/controller/layout.ts
- packages/element/jest.config.js
- packages/element/package.json
- packages/element/src/nodes/donut.ts
- packages/g6/package.json
- packages/g6/src/index.ts
- packages/pc/package.json
- packages/pc/src/global.ts
- packages/pc/src/graph/controller/layout.ts
- packages/pc/src/graph/tree-graph.ts
- packages/pc/src/interface/graph.ts
- packages/pc/tests/unit/behavior/drag-combo-spec.ts
- packages/pc/tests/unit/graph/svg-spec.ts
- packages/pc/tests/unit/layout-preset-spec.ts
- packages/plugin/jest.config.js
- packages/plugin/package.json
- packages/site/docs/api/treeGraphLayout/guide.en.md
- packages/site/docs/api/treeGraphLayout/guide.zh.md
- packages/site/docs/manual/middle/layout/tree-graph-layout.en.md
- packages/site/docs/manual/middle/layout/tree-graph-layout.zh.md
* fix: preset layout with gpu layout;
* fix: isBig must be number for use in path (antvis#4306)
* fix: Fixed issue of nested child combo being rendered under parent, preventing interation with it (antvis#4310)
* fix: Node dragging starting one event too late. (antvis#4365)
* fix: large graph demo page (antvis#4321)
* fix: Node dragging starting one event too late.
---------
Co-authored-by: Yanyan Wang <yanyanwang93@gmail.com>
* feat: tree graph layout with excludeInvisibles prop, closes: antvis#4340; fix: type problems, closes: antvis#4301;
* docs: update change log and site docs
* chore: refine
---------
Co-authored-by: ensconced <joe.barnett876@gmail.com>
Co-authored-by: Gary McGovern <gary.mcgovern@siren.io>
Co-authored-by: Kevin Fontanari <kevin.fontanari@gmail.com>
> sync with upstream

- packages/core/package.json
- packages/core/src/global.ts
- packages/element/package.json
- packages/g6/package.json
- packages/g6/src/index.ts
- packages/pc/package.json
- packages/pc/src/global.ts
- packages/plugin/package.json
- packages/react-node/package.json
- packages/site/package.json
> Bump to 4.8.8-siren.1

- packages/core/src/graph/graph.ts
- packages/core/src/util/validation.ts
- packages/pc/src/graph/controller/layout.ts
> [INVE-24810] Improve dataValidation function

- packages/core/src/graph/graph.ts
- packages/core/src/util/validation.ts
- packages/core/tests/unit/graph/graph-combo-spec.ts
This fixes the issue causing https://sirensolutions.atlassian.net/browse/INVE-25688
> [INVE-25688] Ensure only one vedge connects a combo to a node

- ci/Jenkinsfile
- packages/core/package.json
- packages/element/package.json
- packages/g6/package.json
- packages/pc/package.json
- packages/plugin/package.json
- packages/react-node/package.json
- packages/site/package.json
> [INVE-24705] - Update jenkins file and bump version

- yarn.lock
> [INVE-24705] - Update lockfile to match version bump

- packages/pc/src/behavior/drag-combo.ts
- packages/pc/tests/unit/behavior/drag-combo-spec.ts
> [INVE-26619] Support locked combos in drag-combo behavior
